update CI/CD workflow.

diff --git a/.github/workflows/build_mobile_apk.yml b/.github/workflows/build_mobile_apk.yml
--- a/.github/workflows/build_mobile_apk.yml
+++ b/.github/workflows/build_mobile_apk.yml
@@ -38,7 +38,16 @@ jobs:
       - name: Prepare signing files
         run: |
           echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > app/qsl_manage_mobile/android/android-signing.jks
+          chmod 644 app/qsl_manage_mobile/android/android-signing.jks
+          if [ ! -f "app/qsl_manage_mobile/android/android-signing.jks" ]; then
+            echo "Error: 签名文件生成失败"
+            exit 1
+          fi
           echo "${{ secrets.KEYSTORE_PROPERTIES }}" > app/qsl_manage_mobile/android/key.properties
+          if [ ! -f "app/qsl_manage_mobile/android/key.properties" ]; then
+            echo "Error: key.properties生成失败"
+            exit 1
+          fi
 
 
       # 构建arm64架构 (arm64-v8a)
